# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "meta-vocus"
BBFILE_PATTERN_meta-vocus = "^${LAYERDIR}/"
BBFILE_PRIORITY_meta-vocus = "9"

LAYERDEPENDS_meta-vocus = "core"
LAYERSERIES_COMPAT_meta-vocus = "mickledore"

IMAGE_INSTALL += " dht-web"
IMAGE_INSTALL += " python3"
